plugins {
    id 'net.researchgate.release' version '3.1.0' apply false
    id 'com.gradleup.shadow' version '9.6.1' apply false
    id 'com.github.spotbugs' version '6.5.11' apply false

    id 'io.github.gradle-nexus.publish-plugin' version '2.0.0'
}

defaultTasks 'clean',
        'javadoc',
        'test',
        'check',
        'checkstyleMain',
        'checkstyleTest',
        'assemble',
        'shadowJar'


nexusPublishing {
    repositories {
        sonatype {
            nexusUrl.set(
                    uri('https://ossrh-staging-api.central.sonatype.com/service/local/')
            )

            snapshotRepositoryUrl.set(
                    uri('https://central.sonatype.com/repository/maven-snapshots/')
            )

            username.set(
                    providers.gradleProperty('mavenCentralUsername')
            )

            password.set(
                    providers.gradleProperty('mavenCentralPassword')
            )
        }
    }
}


group = 'de.textmode.pcldumper'
version = '1.5'


subprojects {

    apply plugin: 'java'
    apply plugin: 'eclipse'
    apply plugin: 'checkstyle'
    apply plugin: 'jacoco'
    apply plugin: 'maven-publish'
    apply plugin: 'signing'

    apply plugin: 'net.researchgate.release'
    apply plugin: 'com.gradleup.shadow'
    apply plugin: 'com.github.spotbugs'

    group = rootProject.group
    version = rootProject.version

    repositories {
        mavenCentral()
    }

    dependencies {
        implementation 'commons-cli:commons-cli:1.11.0'
        implementation 'commons-io:commons-io:2.22.0'
        implementation 'de.textmode.pclbox:pclbox:2.5'
		
        compileOnly 'com.github.spotbugs:spotbugs-annotations:4.9.8'

        testImplementation 'junit:junit:4.13.2'
        testImplementation 'commons-io:commons-io:2.22.0'
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8

        withSourcesJar()
        withJavadocJar()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = 8
    }

    tasks.withType(Javadoc).configureEach {
        options.encoding = 'UTF-8'
    }

    checkstyle {
        toolVersion = '7.1'
        configFile = rootProject.file('config/checkstyle.xml')
    }

    tasks.named('jacocoTestReport') {
        reports {
            xml.required = true
            html.required = true
        }
    }

    tasks.named('check') {
        dependsOn tasks.named('jacocoTestReport')
    }

    release {
        failOnUnversionedFiles = false
    }

    tasks.named('jar') {
        manifest {
            attributes(
                    'Specification-Title': 'Java command line tool for dumping PCL printer data streams',
                    'Implementation-Title': 'pcldumper',
                    'Implementation-Version': project.version,
                    'Implementation-Vendor': 'https://github.com/michaelknigge/pcldumper',
                    'Main-Class': 'de.textmode.pcldumper.Main',

                    'Created-By':
                            "${System.getProperty('java.version')} " +
                            "(${System.getProperty('java.vendor')})"
            )
        }
    }

    publishing {

        publications {

            mavenJava(MavenPublication) {

                from components.java

                groupId = 'de.textmode.pcldumper'
                artifactId = 'pcldumper'
                version = project.version


                pom {
                    name = 'pcldumper'

                    description = 'Java command line tool for dumping PCL printer data streams'
                    url = 'https://github.com/michaelknigge/pcldumper'

                    licenses {
                        license {
                            name = 'Apache License, Version 2.0'
                            url = 'https://www.apache.org/licenses/LICENSE-2.0.txt'
                            distribution = 'repo'
                        }
                    }

                    developers {
                        developer {
                            id = 'michaelknigge'
                            name = 'Michael Knigge'
                        }
                    }


                    scm {
                        connection = 'scm:git:git://github.com/michaelknigge/pcldumper.git'
                        developerConnection = 'scm:git:ssh://git@github.com/michaelknigge/pcldumper.git'
                        url = 'https://github.com/michaelknigge/pcldumper'
                    }


                    issueManagement {
                        system = 'GitHub'
                        url = 'https://github.com/michaelknigge/pcldumper/issues'
                    }
                }
            }
        }
    }


    signing {

        def signingKey = providers.gradleProperty('signingKey').orNull
        def signingPassword = providers.gradleProperty('signingPassword').orNull

        if (signingKey != null) {
            signingKey = signingKey.replace('\\n', '\n')

            useInMemoryPgpKeys(
                    signingKey,
                    signingPassword
            )
        }

        sign publishing.publications.mavenJava
    }
}
